// Regenerates every copy of the party list from the two sources of truth:
//   preferredInput.json  — the real manifestos, one string per list
//   VECTORS below        — the 0–1 axis profile of each list
//
// Writes: JevQuestionsInput.json (root + function copy), the function's
// parties.json, and src/data/parties.js.
// Run: node scripts/build-parties.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const read = p => readFileSync(new URL(p, root), 'utf8');
const write = (p, body) => writeFileSync(new URL(p, root), body);

/* security · economy · religion · law, 0 = first pole, 1 = second.
   Same judgement call the page describes in the method section. */
const VECTORS = {
  'הליכוד': { security: .88, economy: .78, religion: .62, law: .85 },
  'ישראל ביתנו': { security: .82, economy: .72, religion: .22, law: .48 },
  'הציונות הדתית': { security: .92, economy: .68, religion: .93, law: .88 },
  'עוצמה יהודית': { security: .97, economy: .62, religion: .88, law: .92 },
  'הימין הממלכתי': { security: .88, economy: .72, religion: .55, law: .60 },
  'נעם': { security: .95, economy: .40, religion: .98, law: .92 },
  'זהות': { security: .80, economy: .97, religion: .10, law: .95 },
  'ביחד': { security: .72, economy: .60, religion: .42, law: .25 },
  'כחול לבן – המחנה הממלכתי': { security: .68, economy: .55, religion: .40, law: .28 },
  'הדמוקרטים': { security: .35, economy: .22, religion: .15, law: .10 },
  'ישר!': { security: .70, economy: .52, religion: .35, law: .22 },
  'בית ציוני': { security: .78, economy: .55, religion: .35, law: .25 },
  'ש״ס': { security: .62, economy: .30, religion: .95, law: .70 },
  'יהדות התורה': { security: .58, economy: .32, religion: .97, law: .78 },
  'רע״ם – הרשימה הערבית המאוחדת': { security: .30, economy: .28, religion: .62, law: .12 },
  'חד״ש-תע״ל': { security: .12, economy: .10, religion: .08, law: .05 },
  'בל״ד – הברית הלאומית הדמוקרטית': { security: .05, economy: .15, religion: .05, law: .02 }
};

const manifestos = JSON.parse(read('preferredInput.json'));
const parties = Object.entries(manifestos).map(([name, manifesto]) => {
  const v = VECTORS[name];
  const leader = manifesto.match(/^מנהיגות:\s*([^.]+)\./)?.[1]?.trim();
  if (!v) throw new Error(`no axis vector for ${name} — add it to VECTORS`);
  if (!leader) throw new Error(`no leader in the manifesto of ${name}`);
  return { name, leader, v, manifesto };
});

/* What JEV scores against: the manifestos exactly as written in
   preferredInput.json. Nothing is prepended, appended or rewritten. */
const questions = {
  'Party to elect': {
    type: 'choice',
    instructions: 'Which party should I elect?',
    criteria: Object.fromEntries(parties.map(p => [p.name, p.manifesto]))
  }
};

const pct = v => Object.fromEntries(Object.entries(v).map(([k, n]) => [k, Math.round(n * 100)]));

write('JevQuestionsInput.json', JSON.stringify(questions, null, 2) + '\n');
write('supabase/functions/jev-questions/JevQuestionsInput.json', JSON.stringify(questions, null, 2) + '\n');
write('supabase/functions/jev-questions/parties.json',
  JSON.stringify(parties.map(({ name, leader, v }) => ({ name, leader, v: pct(v) })), null, 2) + '\n');
write('src/data/parties.js', `/* Generated by scripts/build-parties.mjs from preferredInput.json — do not edit by hand.

   The 17 real 2026 lists with a coarse 0–1 position on each of the four
   axes. The mapping is a judgement call from public platforms, which is why
   the page says so rather than presenting it as a poll. */
export const PARTIES = [
${parties.map(p => `  { name: '${p.name.replace(/'/g, "\\'")}', leader: '${p.leader.replace(/'/g, "\\'")}', v: { ${Object.entries(p.v).map(([k, n]) => `${k}: ${String(n).replace(/^0/, '')}`).join(', ')} } }`).join(',\n')}
];
`);

console.log(`wrote ${parties.length} lists`);
